name = "Legate"
uuid = "1238f2cf-6593-4d60-9aca-2f5364e49909"
version = "0.1.0"

[deps]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"
LegatePreferences = "8028f36a-2b64-49e9-aa04-2d0933fd2ed9"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
legate_jl_wrapper_jll = "6e093c14-372f-5516-b4d7-a6ce14f1038b"
legate_jll = "e95fb1d3-fb9e-51b5-bdb8-1a812408cac9"
libcxxwrap_julia_jll = "3eaa8342-bff7-56a5-9981-c04077f7cee7"

[compat]
CxxWrap = "0.17"
LegatePreferences = "0.1.3"
julia = "1.10"
legate_jl_wrapper_jll = "25.08 - 25.09"
legate_jll = "25.08 - 25.09"
